CREATE DATABASE SaldoSimples;
GO

USE SaldoSimples;
GO

CREATE TABLE Users (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  UserName VARCHAR(100) NOT NULL,
  CPF VARCHAR (11) NOT NULL UNIQUE,
  Email VARCHAR(100) NOT NULL UNIQUE,
  Senha VARBINARY(32) NULL,
  Foto VARCHAR(max) NULL,
  DataCriacao DATETIME2 NOT NULL DEFAULT GETDATE(),
  DataAtualizacao DATETIME2 NOT NULL DEFAULT GETDATE()
);

CREATE TABLE Despesa (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  Categoria VARCHAR(100) NOT NULL,
  Valor DECIMAL(12,2) NOT NULL,
  Recorrente BIT NOT NULL,
  DataCriacao DATETIME2 NOT NULL DEFAULT GETDATE(),
  DataAtualizacao DATETIME2 NOT NULL DEFAULT GETDATE(),
  UserId int,
  CONSTRAINT FK_Despesa_UserId FOREIGN KEY (UserId)
  REFERENCES Users(Id)
);

CREATE TABLE Receita (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  Valor DECIMAL(12,2) NOT NULL,
  OrigemReceita VARCHAR(100) NOT NULL,
  Recorrente BIT NOT NULL,
  DataCriacao DATETIME2 NOT NULL DEFAULT GETDATE(),
  DataAtualizacao DATETIME2 NOT NULL DEFAULT GETDATE(),
  UserId int,
  CONSTRAINT FK_Receita_UserId FOREIGN KEY (UserId)
  REFERENCES Users(Id)
);

CREATE TABLE Orcamento (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  Saldo DECIMAL(12,2) NOT NULL,
  Meta DECIMAL(12,2) NOT NULL,
  Categoria VARCHAR(100) NOT NULL,
  Recorrente BIT NOT NULL,
  DataCriacao DATETIME2 DEFAULT GETDATE(),
  DataAtualizacao DATETIME2 DEFAULT GETDATE(),
  UserId int,
  CONSTRAINT FK_Orcamento_UserId FOREIGN KEY (UserId)
  REFERENCES Users(Id)
);

CREATE TABLE Insight (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  Titulo VARCHAR(100) NOT NULL,
  Categoria VARCHAR(300),
  Descricao VARCHAR(max) NOT NULL,
  DataCriacao DATETIME2 NOT NULL DEFAULT GETDATE(),
  DataAtualizacao DATETIME2 NOT NULL DEFAULT GETDATE(),
  OrcamentoId int,
  CONSTRAINT FK_Insight_UserId FOREIGN KEY (OrcamentoId)
  REFERENCES Orcamento(Id)
);